name: Release changelog

on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    uses: clouddrove/github-shared-workflows/.github/workflows/release-changelog.yml@fix/workflows-docs
    with:
      branch: master
      tag_format: X.Y.Z
      release_tag: ${{ github.ref_name }}
    secrets:
      token: ${{ secrets.TOKEN_GITHUB }}
