name: Update Major Tag

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Extract version
        id: version
        run: |
          TAG=${GITHUB_REF#refs/tags/}

          echo "Release tag: $TAG"

          MAJOR=$(echo $TAG | cut -d. -f1)

          echo "major_tag=$MAJOR" >> $GITHUB_OUTPUT

      - name: Update major tag
        run: |
          git tag -f ${{ steps.version.outputs.major_tag }} ${{ github.ref_name }}

      - name: Push major tag
        run: |
          git push origin ${{ steps.version.outputs.major_tag }} --force